### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by stibbs109** [standardebooks/baroness-orczy_the-scarlet-pimpernel#3]
Hello, 

Many thanks to the Standard Ebooks team for producing "The Scarlet Pimpernel" Ebook.
I've noticed some typos which I'd like to report. The typos are listed below in context so they are easily searchable.

Kind regards,
stibbs109

Typos:

Hair-breath escapes

vague memories, that were sweet and ardent and attuned to this calm summer’s evening, came wafted back to her memory, 

St.Cyr had perished through a thoughtless words of hers;

**Comment by acabal** [comment]
Thanks! The 2nd item is as-is in print, the other two are typos. I've gone ahead and fixed them.
